// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remoting_api.proto

package com.hyf.hotrefresh.plugin.grpc.generate;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotrefresh.v1.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>bytes encoding = 2;</code>
   * @return The encoding.
   */
  com.google.protobuf.ByteString getEncoding();

  /**
   * <code>bytes codec = 3;</code>
   * @return The codec.
   */
  com.google.protobuf.ByteString getCodec();

  /**
   * <code>bytes compress = 4;</code>
   * @return The compress.
   */
  com.google.protobuf.ByteString getCompress();

  /**
   * <code>bytes messageType = 5;</code>
   * @return The messageType.
   */
  com.google.protobuf.ByteString getMessageType();

  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  int getMetadataCount();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  boolean containsMetadata(
      String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getMetadata();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  java.util.Map<String, String>
  getMetadataMap();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */

  String getMetadataOrDefault(
      String key,
      String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */

  String getMetadataOrThrow(
      String key);

  /**
   * <code>.google.protobuf.Any body = 7;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>.google.protobuf.Any body = 7;</code>
   * @return The body.
   */
  com.google.protobuf.Any getBody();
  /**
   * <code>.google.protobuf.Any body = 7;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
