// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remoting_api.proto

package com.hyf.hotrefresh.plugin.grpc.generate;

public final class RemotingApiProto {
  private RemotingApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotrefresh_v1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotrefresh_v1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotrefresh_v1_Message_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotrefresh_v1_Message_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022remoting_api.proto\022\rhotrefresh.v1\032\031goo" +
      "gle/protobuf/any.proto\"\352\001\n\007Message\022\n\n\002id" +
      "\030\001 \001(\005\022\020\n\010encoding\030\002 \001(\014\022\r\n\005codec\030\003 \001(\014\022" +
      "\020\n\010compress\030\004 \001(\014\022\023\n\013messageType\030\005 \001(\014\0226" +
      "\n\010metadata\030\006 \003(\0132$.hotrefresh.v1.Message" +
      ".MetadataEntry\022\"\n\004body\030\007 \001(\0132\024.google.pr" +
      "otobuf.Any\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\0012\217\002\n\013RemotingApi\0229\n\007R" +
      "equest\022\026.hotrefresh.v1.Message\032\026.hotrefr" +
      "esh.v1.Message\022A\n\rRequestStream\022\026.hotref" +
      "resh.v1.Message\032\026.hotrefresh.v1.Message(" +
      "\001\022B\n\016ResponseStream\022\026.hotrefresh.v1.Mess" +
      "age\032\026.hotrefresh.v1.Message0\001\022>\n\010BiStrea" +
      "m\022\026.hotrefresh.v1.Message\032\026.hotrefresh.v" +
      "1.Message(\0010\001B=\n\'com.hyf.hotrefresh.plug" +
      "in.grpc.generateB\020RemotingApiProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_hotrefresh_v1_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hotrefresh_v1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotrefresh_v1_Message_descriptor,
        new String[] { "Id", "Encoding", "Codec", "Compress", "MessageType", "Metadata", "Body", });
    internal_static_hotrefresh_v1_Message_MetadataEntry_descriptor =
      internal_static_hotrefresh_v1_Message_descriptor.getNestedTypes().get(0);
    internal_static_hotrefresh_v1_Message_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotrefresh_v1_Message_MetadataEntry_descriptor,
        new String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
